# Bluestock MF Capstone

## Notebook 01 - Data Ingestion

### Objectives

- Load all 10 raw datasets
- Understand dataset structure
- Check missing values
- Check duplicates
- Perform initial profiling

In [1]:
from pathlib import Path
import pandas as pd
import os

In [2]:
BASE_DIR = Path.cwd().parent

folder = BASE_DIR / "data" / "raw"

print(f"Reading files from: {folder}")

Reading files from: c:\Users\lambd\Desktop\BlueStock_project\bluestock_mf_capstone\data\raw

## Dataset Inventory

The project contains 10 mutual fund datasets collected from AMFI and related sources.

In [3]:
files = sorted(os.listdir(folder))

for file in files:
    
    if file.endswith(".csv"):
        
        print(file)

01_fund_master.csv
02_nav_history.csv
03_aum_by_fund_house.csv
04_monthly_sip_inflows.csv
05_category_inflows.csv
06_industry_folio_count.csv
07_scheme_performance.csv
08_investor_transactions.csv
09_portfolio_holdings.csv
10_benchmark_indices.csv
125497_live_nav.csv
combined_live_nav.csv

## Dataset Summary

Display row and column counts for every dataset.

In [4]:
summary = []

for file in os.listdir(folder):

    if file.endswith(".csv"):

        file_path = folder / file

        df = pd.read_csv(file_path)

        summary.append({
            "Dataset": file,
            "Rows": df.shape[0],
            "Columns": df.shape[1]
        })

summary_df = pd.DataFrame(summary)

summary_df

                         Dataset   Rows  Columns
0             01_fund_master.csv     40       15
1             02_nav_history.csv  46000        3
2       03_aum_by_fund_house.csv     90        5
3     04_monthly_sip_inflows.csv     48        6
4        05_category_inflows.csv    144        3
5    06_industry_folio_count.csv     21        6
6      07_scheme_performance.csv     40       19
7   08_investor_transactions.csv  32778       13
8      09_portfolio_holdings.csv    322        8
9       10_benchmark_indices.csv   8050        3
10           125497_live_nav.csv      1        8
11         combined_live_nav.csv      5        8

## Data Profiling

For each dataset:

- Shape
- Columns
- Missing Values
- Duplicate Records

In [5]:
for file in os.listdir(folder):

    if file.endswith(".csv"):

        file_path = folder / file

        df = pd.read_csv(file_path)

        print("\n" + "="*60)
        print(file)

        print("Shape:", df.shape)

        print("Columns:")
        print(list(df.columns))

        print("\nMissing Values:")
        print(df.isnull().sum())

        print("\nDuplicates:")
        print(df.duplicated().sum())

============================================================
01_fund_master.csv
Shape: (40, 15)
Columns:
['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category', 'plan', 'launch_date', 'benchmark', 'expense_ratio_pct', 'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager', 'risk_category', 'sebi_category_code']

Missing Values:
amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

Duplicates:
0

============================================================
02_nav_history.csv
Shape: (46000, 3)
Columns:
['amfi_code', 'date', 'nav']

Missing Values:
amfi_code    0
date         0
nav          0
dtype: int64

Duplicates:
0

============================================================
03_aum_by_fund_house.csv
Shape: (90, 5)
Columns:
['date', 'fund_house', 'aum_lakh_crore', 'aum_crore', 'num_schemes']

Missing Values:
date              0
fund_house        0
aum_lakh_crore    0
aum_crore         0
num_schemes       0
dtype: int64

Duplicates:
0

============================================================
04_monthly_sip_inflows.csv
Shape: (48, 6)
Columns:
['month', 'sip_inflow_crore', 'active_sip_accounts_crore', 'new_sip_accounts_lakh', 'sip_aum_lakh_crore', 'yoy_growth_pct']

Missing Values:
month                         0
sip_inflow_crore              0
active_sip_accounts_crore     0
new_sip_accounts_lakh         0
sip_aum_lakh_crore            0
yoy_growth_pct               12
dtype: int64

Duplicates:
0

============================================================
05_category_inflows.csv
Shape: (144, 3)
Columns:
['month', 'category', 'net_inflow_crore']

Missing Values:
month               0
category            0
net_inflow_crore    0
dtype: int64

Duplicates:
0

============================================================
06_industry_folio_count.csv
Shape: (21, 6)
Columns:
['month', 'total_folios_crore', 'equity_folios_crore', 'debt_folios_crore', 'hybrid_folios_crore', 'others_folios_crore']

Missing Values:
month                  0
total_folios_crore     0
equity_folios_crore    0
debt_folios_crore      0
hybrid_folios_crore    0
others_folios_crore    0
dtype: int64

Duplicates:
0

============================================================
07_scheme_performance.csv
Shape: (40, 19)
Columns:
['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan', 'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct', 'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio', 'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct', 'morningstar_rating', 'risk_grade']

Missing Values:
amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

Duplicates:
0

============================================================
08_investor_transactions.csv
Shape: (32778, 13)
Columns:
['investor_id', 'transaction_date', 'amfi_code', 'transaction_type', 'amount_inr', 'state', 'city', 'city_tier', 'age_group', 'gender', 'annual_income_lakh', 'payment_mode', 'kyc_status']

Missing Values:
investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

Duplicates:
0

============================================================
09_portfolio_holdings.csv
Shape: (322, 8)
Columns:
['amfi_code', 'stock_symbol', 'stock_name', 'sector', 'weight_pct', 'market_value_cr', 'current_price_inr', 'portfolio_date']

Missing Values:
amfi_code            0
stock_symbol         0
stock_name           0
sector               0
weight_pct           0
market_value_cr      0
current_price_inr    0
portfolio_date       0
dtype: int64

Duplicates:
0

============================================================
10_benchmark_indices.csv
Shape: (8050, 3)
Columns:
['date', 'index_name', 'close_value']

Missing Values:
date           0
index_name     0
close_value    0
dtype: int64

Duplicates:
0

============================================================
125497_live_nav.csv
Shape: (1, 8)
Columns:
['scheme_code', 'scheme_name', 'fund_house', 'scheme_type', 'scheme_category', 'latest_nav', 'nav_date', 'api_fetch_timestamp']

Missing Values:
scheme_code            0
scheme_name            0
fund_house             0
scheme_type            0
scheme_category        0
latest_nav             0
nav_date               0
api_fetch_timestamp    0
dtype: int64

Duplicates:
0

============================================================
combined_live_nav.csv
Shape: (5, 8)
Columns:
['amfi_code', 'scheme_name', 'fund_house', 'scheme_type', 'scheme_category', 'latest_nav', 'nav_date', 'api_fetch_timestamp']

Missing Values:
amfi_code              0
scheme_name            0
fund_house             0
scheme_type            0
scheme_category        0
latest_nav             0
nav_date               0
api_fetch_timestamp    0
dtype: int64

Duplicates:
0

## Dataset Preview

Inspect the first five rows of each dataset.

In [6]:
for file in os.listdir(folder):

    if file.endswith(".csv"):

        print("\n" + "="*60)
        print(file)

        df = pd.read_csv(folder / file)

        display(df.head())

============================================================
01_fund_master.csv

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

============================================================
02_nav_history.csv

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

============================================================
03_aum_by_fund_house.csv

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

============================================================
04_monthly_sip_inflows.csv

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN

============================================================
05_category_inflows.csv

     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0

============================================================
06_industry_folio_count.csv

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01,13.26,9.28,1.86,0.80,1.33
1,2022-04,13.91,9.74,1.95,0.83,1.39
2,2022-07,13.85,9.69,1.94,0.83,1.38
3,2022-10,14.12,9.88,1.98,0.85,1.41
4,2023-01,14.81,10.37,2.07,0.89,1.48

============================================================
07_scheme_performance.csv

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

============================================================
08_investor_transactions.csv

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

============================================================
09_portfolio_holdings.csv

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

============================================================
10_benchmark_indices.csv

         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

============================================================
125497_live_nav.csv

,scheme_code,scheme_name,fund_house,scheme_type,scheme_category,latest_nav,nav_date,api_fetch_timestamp
0,125497,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Open Ended Schemes,Equity Scheme - Small Cap Fund,192.3195,01-06-2026,2026-06-02 16:42:51.682034

============================================================
combined_live_nav.csv

,amfi_code,scheme_name,fund_house,scheme_type,scheme_category,latest_nav,nav_date,api_fetch_timestamp
0,119551,Aditya Birla Sun Life Banking & PSU Debt Fund ...,Aditya Birla Sun Life Mutual Fund,Open Ended Schemes,Debt Scheme - Banking and PSU Fund,104.7025,01-06-2026,2026-06-02 16:49:59.929881
1,120503,Axis ELSS Tax Saver Fund - Direct Plan - Growt...,Axis Mutual Fund,Open Ended Schemes,Equity Scheme - ELSS,103.0948,01-06-2026,2026-06-02 16:50:00.343732
2,118632,Nippon India Large Cap Fund - Direct Plan Grow...,Nippon India Mutual Fund,Open Ended Schemes,Equity Scheme - Large Cap Fund,97.1944,01-06-2026,2026-06-02 16:50:00.649977
3,119092,HDFC Money Market Fund - Growth Option - Direc...,HDFC Mutual Fund,Open Ended Schemes,Debt Scheme - Money Market Fund,6156.7532,01-06-2026,2026-06-02 16:50:01.061040
4,120841,quant Mid Cap Fund - Growth Option - Direct Plan,quant Mutual Fund,Open Ended Schemes,Equity Scheme - Mid Cap Fund,246.9814,01-06-2026,2026-06-02 16:50:01.427963

## Data Quality Observations

The ingestion process successfully loaded all raw datasets.

Checks performed:

- Dataset dimensions verified
- Column structures reviewed
- Missing values identified
- Duplicate records measured

The datasets are ready for cleaning and validation.

# Day 1 Summary

### Completed

✅ Environment Setup

✅ Dataset Ingestion

✅ Initial Profiling

✅ Missing Value Assessment

✅ Duplicate Detection

### Next Step

Proceed to Notebook 02: Data Cleaning and SQL Warehouse Design.